// importamos la función `example`
import {
  // eslint-disable-next-line max-len
  seeToChampion, filterType, championsInFallingPower, championsInUpwardPower, championsInFallingUtility, championsInUpwardUtility, championsInFallingDifficult, championsInUpwardDifficult, searchWord,
} from '../src/data.js';

const dataLol = [
  {
    version: '6.24.1',
    id: 'Aatrox',
    key: '266',
    name: 'Aatrox',
    title: 'the Darkin Blade',
    img:
      'https://www.masterypoints.com/assets/img/lol/champion_icons/Aatrox.png',
    splash:
      'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
    blurb:
      "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
    info: {
      attack: 8,
      defense: 4,
      magic: 3,
      difficulty: 4,
    },
    image: {
      full: 'Aatrox.png',
      sprite: 'champion0.png',
      group: 'champion',
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ['Fighter', 'Tank'],
    partype: 'BloodWell',
    stats: {
      hp: 537.8,
      hpperlevel: 85,
      mp: 105.6,
      mpperlevel: 45,
      movespeed: 345,
      armor: 24.384,
      armorperlevel: 3.8,
      spellblock: 32.1,
      spellblockperlevel: 1.25,
      attackrange: 150,
      hpregen: 6.59,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60.376,
      attackdamageperlevel: 3.2,
      attackspeedoffset: -0.04,
      attackspeedperlevel: 3,
    },
  },
  {
    version: '6.24.1',
    id: 'Ahri',
    key: '103',
    name: 'Ahri',
    title: 'the Nine-Tailed Fox',
    img:
      'https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png',
    splash:
      'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
    blurb:
      'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
    info: {
      attack: 3,
      defense: 4,
      magic: 8,
      difficulty: 5,
    },
    image: {
      full: 'Ahri.png',
      sprite: 'champion0.png',
      group: 'champion',
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ['Mage', 'Assassin'],
    partype: 'MP',
    stats: {
      hp: 514.4,
      hpperlevel: 80,
      mp: 334,
      mpperlevel: 50,
      movespeed: 330,
      armor: 20.88,
      armorperlevel: 3.5,
      spellblock: 30,
      spellblockperlevel: 0,
      attackrange: 550,
      hpregen: 6.505,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53.04,
      attackdamageperlevel: 3,
      attackspeedoffset: -0.065,
      attackspeedperlevel: 2,
    },
  },
  {
    version: '6.24.1',
    id: 'Akali',
    key: '84',
    name: 'Akali',
    title: 'the Fist of Shadow',
    img:
      'https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png',
    splash:
      'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
    blurb:
      'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
    info: {
      attack: 5,
      defense: 3,
      magic: 8,
      difficulty: 7,
    },
    image: {
      full: 'Akali.png',
      sprite: 'champion0.png',
      group: 'champion',
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ['Assassin'],
    partype: 'Energy',
    stats: {
      hp: 587.8,
      hpperlevel: 85,
      mp: 200,
      mpperlevel: 0,
      movespeed: 350,
      armor: 26.38,
      armorperlevel: 3.5,
      spellblock: 32.1,
      spellblockperlevel: 1.25,
      attackrange: 125,
      hpregen: 8.34,
      hpregenperlevel: 0.65,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 58.376,
      attackdamageperlevel: 3.2,
      attackspeedoffset: -0.1,
      attackspeedperlevel: 3.1,
    },
  },
  {
    version: '6.24.1',
    id: 'Alistar',
    key: '12',
    name: 'Alistar',
    title: 'the Minotaur',
    img:
      'https://www.masterypoints.com/assets/img/lol/champion_icons/Alistar.png',
    splash:
      'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
    blurb:
      "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
    info: {
      attack: 6,
      defense: 9,
      magic: 5,
      difficulty: 7,
    },
    image: {
      full: 'Alistar.png',
      sprite: 'champion0.png',
      group: 'champion',
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ['Tank', 'Support'],
    partype: 'MP',
    stats: {
      hp: 613.36,
      hpperlevel: 106,
      mp: 278.84,
      mpperlevel: 38,
      movespeed: 330,
      armor: 24.38,
      armorperlevel: 3.5,
      spellblock: 32.1,
      spellblockperlevel: 1.25,
      attackrange: 125,
      hpregen: 8.675,
      hpregenperlevel: 0.85,
      mpregen: 8.5,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 61.1116,
      attackdamageperlevel: 3.62,
      attackspeedoffset: 0,
      attackspeedperlevel: 2.125,
    },
  },
];
const newDataLol = [
  {
    name: 'Aatrox',
    title: 'the Darkin Blade',
    image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
    blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
    power: 8,
    defense: 4,
    magic: 3,
    difficulty: 4,
    tag1: 'Fighter',
    tag2: 'Tank',
    levelLife: 85,
    moveSpeed: 345,
    armor: 24.384,
    spellblock: 32.1,
    stats4: 150,
    stats5: 60.376,
    stats6: 3,
  },
  {
    name: 'Ahri',
    title: 'the Nine-Tailed Fox',
    image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
    blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
    power: 3,
    defense: 4,
    magic: 8,
    difficulty: 5,
    tag1: 'Mage',
    tag2: 'Assassin',
    levelLife: 80,
    moveSpeed: 330,
    armor: 20.88,
    spellblock: 30,
    stats4: 550,
    stats5: 53.04,
    stats6: 2,
  },
  {
    name: 'Akali',
    title: 'the Fist of Shadow',
    image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
    blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
    power: 5,
    defense: 3,
    magic: 8,
    difficulty: 7,
    tag1: 'Assassin',
    tag2: undefined,
    levelLife: 85,
    moveSpeed: 350,
    armor: 26.38,
    spellblock: 32.1,
    stats4: 125,
    stats5: 58.376,
    stats6: 3.1,
  },
  {
    name: 'Alistar',
    title: 'the Minotaur',
    image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
    blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
    power: 6,
    defense: 9,
    magic: 5,
    difficulty: 7,
    tag1: 'Tank',
    tag2: 'Support',
    levelLife: 106,
    moveSpeed: 330,
    armor: 24.38,
    spellblock: 32.1,
    stats4: 125,
    stats5: 61.1116,
    stats6: 2.125,
  },
];

describe('seeToChampion', () => {
  it('debería ser una función', () => {
    expect(typeof seeToChampion).toBe('function');
  });

  it('debería extraer información cada campeón', () => {
    // eslint-disable-next-line jest/valid-expect
    expect(seeToChampion(dataLol)).toMatchObject([
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
    ]);
  });
});

describe('filterType', () => {
  it('debería ser una función', () => {
    expect(typeof filterType).toBe('function');
  });

  it('debería filtrar por tipo de campeón', () => {
    // eslint-disable-next-line no-console
    console.log(filterType(newDataLol, 'Tank'));
    // eslint-disable-next-line jest/valid-expect
    expect(filterType(newDataLol, 'Tank')).toMatchObject([
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
    ]);
  });
});

describe('championsInFallingPower', () => {
  it('debería ser una función', () => {
    expect(typeof championsInFallingPower).toBe('function');
  });

  it('ordena a los campeones de forma descendente en la caracteritica de poder', () => {
    // eslint-disable-next-line no-undef
    expect(championsInFallingPower(newDataLol, 'falling')).toMatchObject([
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
    ]);
  });
});

describe('championsInUpwardPower', () => {
  it('debería ser una función', () => {
    expect(typeof championsInUpwardPower).toBe('function');
  });

  it('ordena a los campeones de forma ascendente en la caracteritica de poder', () => {
    // eslint-disable-next-line no-undef
    expect(championsInUpwardPower(newDataLol, 'upward')).toMatchObject([
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
    ]);
  });
});

describe('championsInFallingUtility', () => {
  it('debería ser una función', () => {
    expect(typeof championsInFallingUtility).toBe('function');
  });

  it('ordena a los campeones de forma descendente en la caracteritica de defensa', () => {
    // eslint-disable-next-line no-undef
    expect(championsInFallingUtility(newDataLol, 'falling')).toMatchObject([
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
    ]);
  });
});

describe('championsInUpwardUtility', () => {
  it('debería ser una función', () => {
    expect(typeof championsInUpwardUtility).toBe('function');
  });

  it('ordena a los campeones de forma ascendente en la caracteritica de defensa', () => {
    // eslint-disable-next-line no-undef
    expect(championsInUpwardUtility(newDataLol, 'upward')).toMatchObject([
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
    ]);
  });
});

describe('championsInFallingDifficult', () => {
  it('debería ser una función', () => {
    expect(typeof championsInFallingDifficult).toBe('function');
  });

  it('ordena a los campeones de forma descendente en la caracteritica de dificultad', () => {
    // eslint-disable-next-line no-undef
    expect(championsInFallingDifficult(newDataLol, 'falling')).toMatchObject([
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
    ]);
  });
});

describe('championsInUpwardDifficult', () => {
  it('debería ser una función', () => {
    expect(typeof championsInUpwardDifficult).toBe('function');
  });

  it('ordena a los campeones de forma ascendente en la caracteritica de dificultad', () => {
    // eslint-disable-next-line no-undef
    expect(championsInUpwardDifficult(newDataLol, 'upward')).toMatchObject([
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
    ]);
  });
});

describe('searchWord', () => {
  it('debería ser una función', () => {
    expect(typeof searchWord).toBe('function');
  });

  it('ordena a los campeones de forma ascendente en la caracteritica de dificultad', () => {
    // eslint-disable-next-line no-undef
    expect(searchWord(newDataLol, 'a')).toMatchObject([
      {
        name: 'Aatrox',
        title: 'the Darkin Blade',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's ...",
        power: 8,
        defense: 4,
        magic: 3,
        difficulty: 4,
        tag1: 'Fighter',
        tag2: 'Tank',
        levelLife: 85,
        moveSpeed: 345,
        armor: 24.384,
        spellblock: 32.1,
        stats4: 150,
        stats5: 60.376,
        stats6: 3,
      },
      {
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        power: 3,
        defense: 4,
        magic: 8,
        difficulty: 5,
        tag1: 'Mage',
        tag2: 'Assassin',
        levelLife: 80,
        moveSpeed: 330,
        armor: 20.88,
        spellblock: 30,
        stats4: 550,
        stats5: 53.04,
        stats6: 2,
      },
      {
        name: 'Akali',
        title: 'the Fist of Shadow',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        power: 5,
        defense: 3,
        magic: 8,
        difficulty: 7,
        tag1: 'Assassin',
        tag2: undefined,
        levelLife: 85,
        moveSpeed: 350,
        armor: 26.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 58.376,
        stats6: 3.1,
      },
      {
        name: 'Alistar',
        title: 'the Minotaur',
        image: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        blurb: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of ...",
        power: 6,
        defense: 9,
        magic: 5,
        difficulty: 7,
        tag1: 'Tank',
        tag2: 'Support',
        levelLife: 106,
        moveSpeed: 330,
        armor: 24.38,
        spellblock: 32.1,
        stats4: 125,
        stats5: 61.1116,
        stats6: 2.125,
      },
    ]);
  });
});
